tap "jesseduffield/lazygit"

brew "bat"
brew "diff-so-fancy"
brew "fd"
brew "fzf"
brew "gh"
brew "gist"
brew "git"
brew "httpie"
brew "lazygit"
brew "neovim"
brew "node"
brew "pyenv"
brew "redis"
brew "ripgrep"
brew "sem-cli"
brew "starship"
brew "tmux"
brew "tmuxinator"
brew "zoxide"

cask "ghostty"
cask "font-caskaydia-cove-nerd-font"
cask "font-fira-code-nerd-font"
